# Generated by Django 5.0.6 on 2024-06-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_email_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user_profile',
        ),
    ]
