# Generated by Django 5.0.6 on 2024-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_email_verified_organizationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationOTP',
        ),
    ]
