# Generated by Django 5.0.6 on 2024-06-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_otp_delete_organizationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
