# Generated by Django 5.0.6 on 2024-06-07 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_experience_techstack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Details',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='Studies',
        ),
        migrations.RenameModel(
            old_name='Experience',
            new_name='Working',
        ),
    ]
