# Generated by Django 5.0.6 on 2024-06-12 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0007_remove_working_user_profile_delete_studies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='study_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='techstack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
