# Generated by Django 5.0.6 on 2024-06-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0008_details_company_details_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='details',
            name='study_start_date',
        ),
    ]
