# Generated by Django 5.0.6 on 2024-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0009_remove_details_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
