# Generated by Django 5.0.6 on 2024-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0010_alter_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
