# Generated by Django 5.0.6 on 2024-06-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_userprofile_is_organisation_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_organisation',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
